name: test-list-buckets

on:
  push:
    branches:
      - 1-amazon-bedrock-github-actions

permissions:
  id-token: write
  contents: read

jobs:
  listbuckets:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: ${{ vars.AWS_ROLE }}

      - run: aws s3api list-buckets
